### ISSUE TITLE
HDMI Graphics and Audio Output is not working

### ISSUE THREAD

**Issue by pmtremblay** [Xigtun/xps-9570-mojave#14]
I tried to connect the USB-C (thunderbolt 3 enabled) of my Dell XPS 15 9570 i9 running Mojave 10.14 (not 10.14.1 yet) to my old Apple Cinema Display using a USB-C to Mini-DisplayPort 4K@60Hz CableCreation M/F but it acts like it is not sending any signal. Any idea how I could make this work?

Is there a way to make Thunderbolt 3 to work?

Thanks.

**Comment by eamigo86** [comment]
Any progress with the HDMI output?

**Comment by Xigtun** [comment]
type-c external display shoud worked now
