### ISSUE TITLE
Intel UHD 630 acceleration failed

### ISSUE THREAD

**Issue by Heliopause0916** [Xigtun/xps-9570-mojave#16]
Only shows 31mb memory
I don't know how to fix it
USB, bluetooth work perfectly

**Comment by Heliopause0916** [comment]
Already solved
The problem happened because of my carelessness

**Comment by eamigo86** [comment]
Hello @Heliopause0916 I have the same problem, could you explain how resolve this. Thanks in advance

**Comment by Heliopause0916** [comment]
I have that problem because of using "install_CLOVER" and forgetting to replace it after installation.

Just copy Xigtun's "/EFI/CLOVER" after deleting the one on your ESP (make backup in advance)

Additionally, 1080p screen need to use "config_1080p.plist" instead.
