### ISSUE TITLE
请问有解决开机黑屏三分钟的问题吗？

### ISSUE THREAD

**Issue by DaDaDa12138** [Xigtun/xps-9570-mojave#2]
我的电脑也是9570， 看你这貌似解决了这个黑屏问题，但是我这边还是会黑屏一会。

请问是还需要其他操作吗？

谢谢。

**Comment by Xigtun** [comment]
没有 
参照这个帖子
https://www.tonymacx86.com/threads/bug-black-screen-3-minutes-after-booting-coffeelake-uhd-630.261131/
可以换用 Whatevergreen 试试
但是看结果还没有最后的方案

**Comment by Xigtun** [comment]
已解决
