### ISSUE TITLE
Cannot boot into system after successful installation

### ISSUE THREAD

**Issue by Rakantor** [Xigtun/xps-9570-mojave#22]
I have the 1080p non touchscreen version of the XPS 15 9570 with 16 GB RAM and i7-8750H CPU.

I could install Mojave 10.14.2 successfully. After logging into the system for the first time, I replaced the "CLOVER" and "BOOT" folder in my EFI folder on my hard drive's ESP with the "CLOVER" and "BOOT" folder from the "EFI" folder in this Github repository.
I also deleted "config.plist" and renamed "config_1080p.plist" to "config.plist".
Then I ran "sudo kextcache -i /" without errors.
Then I tried to reboot. I can boot into Clover bootloader without a USB stick and select my installation of Mojave. Then there's a lot of text as usual when booting Mojave, but after a few seconds the screen goes black and my system reboots.

So I changed ig-platform-id to 0x12345678 and tried again - it worked this time. I could boot into Mojave, BUT the system information showed "Intel UHD Graphics 6 MB".
[error_report.docx](https://github.com/Xigtun/xps-9570-mojave/files/2706437/error_report.docx)

I then again changed ig-platform-id back to 0x3e9b0000 and rebooted. It doesn't work, same issue as mentioned before.

I also tried replacing the whole EFI folder on my ESP with the EFI folder you provide, but then I just get a blue screen when booting and the clover bootloader doesn't boot at all.

What can I do?

**Comment by eamigo86** [comment]
Hi @Rakantor, take a look at this guide that give good tips to make hackintosh on the Dell XPS 9570:
[guide](https://github.com/bavariancake/XPS9570-macOS)

**Comment by Rakantor** [comment]
I got it working. The only thing I did was to change this part in the config.plist

`<dict>
        <key>Comment</key>
        <string>Set the maximum link rate in DPCD buffer to 0x0A (HBR) for laptops with 1080p or below display (by FireWolf)</string>
        <key>Disabled</key>
        <false/>
        <key>Find</key>
        <data>
        6AAAAABIg8MESIP7CHLQ
        </data>
        <key>InfoPlistPatch</key>
        <false/>
        <key>Name</key>
        <string>AppleIntelCFLGraphicsFramebuffer</string>
        <key>Replace</key>
        <data>
        QYO8JNwBAAAAdQTGRcEK
        </data>
    </dict>`

to this

`<dict>
				<key>Comment</key>
				<string>ALT: Set the maximum link rate in DPCD buffer to 0x0A (HBR) for laptops with 1080p display (by FireWolf)</string>
				<key>Disabled</key>
				<true/>
				<key>Name</key>
				<string>AppleIntelCFLGraphicsFramebuffer</string>
				<key>Find</key>
				<data>SIPDBEiD+why0A==</data>
				<key>Replace</key>
				<data>gH3BAHUExkXBCg==</data>
				<key>InfoPlistPatch</key>
				<false/>
			</dict>`

The system boots without a problem now and the system info shows "Intel UHD Graphics 2048 MB".
Thanks!
