### ISSUE TITLE
想请教下9570在本身分辨率4k情况下外接4k显示器的效果

### ISSUE THREAD

**Issue by ghost** [Xigtun/xps-9570-mojave#38]
如题，使用起来会明显影响流畅度么？据我所知标压U的核显TDP应该会给的比较充足，而且在黑果下只能核显工作所以散热ok，我2018款mbp13在外接2k显示器之后流畅度难以保障，想问下您现在使用体验如何。

**Comment by Xigtun** [comment]
使用体验很好，没有图片处理与视频编辑的需求

**Comment by ghost** [comment]
好的，感谢您的回复，看来可以放心大胆的入了 :)
