### ISSUE TITLE
HDMI输出问题

### ISSUE THREAD

**Issue by jardenliu** [Xigtun/xps-9570-mojave#4]
HDMI没输出应该是AGDPolicy导致的问题

**Comment by eamigo86** [comment]
Any progress with the HDMI output?

**Comment by eamigo86** [comment]
Hi @jardenliu, that not work for my, any other idea?

**Comment by jardenliu** [comment]
@eamigo86 which SMBIOS did you choose

**Comment by eamigo86** [comment]
Hi @jardenliu, I have selected the MacBookPro15,1 model.

**Comment by jardenliu** [comment]
normally，fix HDMI port and AGDPolicy， then it work

**Comment by eamigo86** [comment]
Hi @jardenliu, I do not understand your recommendation, could be more specific please??? Thanks in advance
